### ISSUE TITLE
Extra feature SN programming has a bug.

### ISSUE THREAD

**Issue by MrKevinWeiss** [inetrg/inet-nm#15]
Likely a my setup issue but I get:
```
Traceback (most recent call last):
  File "/home/weiss/.venv/bin/inet-nm-commission", line 8, in <module>
    sys.exit(main())
  File "/home/weiss/.venv/lib/python3.10/site-packages/inet_nm/cli_commission.py", line 75, in main
    _main()
  File "/home/weiss/.venv/lib/python3.10/site-packages/inet_nm/cli_commission.py", line 66, in _main
    cmr.check_and_set_uninitialized_sn(selected_node)
  File "/home/weiss/.venv/lib/python3.10/site-packages/inet_nm/commissioner.py", line 44, in check_and_set_uninitialized_sn
    if usbdev.serial_number != node.serial:
  File "/home/weiss/.venv/lib/python3.10/site-packages/usb/core.py", line 864, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/home/weiss/.venv/lib/python3.10/site-packages/usb/util.py", line 313, in get_string
    raise ValueError("The device has no langid"
ValueError: The device has no langid (permission issue, no string descriptors supported or device error)
```

**Comment by MrKevinWeiss** [comment]
It seems like it was the udev rules:

https://github.com/pyusb/pyusb/issues/139
